=== KrzysztofKozubek/Academic/SEMESTR VI/XML/Projekt/typy_nienazwane/dtd.dtd
<!ELEMENT FILMY (FILM*)>
<!ELEMENT FILM (tytul?, ocena?, opis?, gatunek?)>
<!ELEMENT tytul (#PCDATA)>
<!ELEMENT ocena (#PCDATA)>
<!ELEMENT opis (#PCDATA)>
<!ELEMENT gatunek (#PCDATA)>

=== KrzysztofKozubek/Academic/SEMESTR VI/XML/Projekt/dtd/file.xml
<?xml version="1.0" encoding="utf-8"?>
        <?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE FILMY SYSTEM "dtd.dtd">

<FILMY>
    <FILM>
        <tytul>Zielona mila</tytul>
        <ocena> 8 / 10 </ocena>
        <opis>Emerytowany strażnik więzienny opowiada przyjaciółce o niezwykłym mężczyźnie, którego skazano na śmierć za zabójstwo dwóch 9-letnich dziewczynek.</opis>
    </FILM>
    <FILM>
        <tytul>Forrest Gump</tytul>
        <ocena> 6 / 10 </ocena>
        <opis>Historia życia Forresta, chłopca o niskim ilorazie inteligencji z niedowładem kończyn, który staje się miliarderem i bohaterem wojny w Wietnamie.</opis>
    </FILM>
    <FILM>
        <tytul >Skazani na Shawshank</tytul>
        <ocena > 7 / 10 </ocena>
        <opis >Adaptacja opowiadania Stephena Kinga. Historia niesłusznie skazanego na dożywocie bankiera, który musi przeżyć w brutalnym świecie rządzonym przez strażników i współwięźniów.</opis>
    </FILM>
    <FILM>
        <tytul >Matrix</tytul>
        <ocena > 8 / 10 </ocena>
        <opis >Haker komputerowy Neo dowiaduje się od tajemniczych rebeliantów, że świat, w którym żyje, jest tylko obrazem przesyłanym do jego mózgu przez roboty.</opis>
    </FILM>
    <FILM>
        <tytul >Leon zawodowiec</tytul>
        <ocena > 8 / 10 </ocena>
        <opis >Płatny morderca ratuje dwunastoletnią dziewczynkę, której rodzina została zabita przez skorumpowanych policjantów.</opis>
    </FILM>
    <FILM>
        <tytul >Shrek</tytul>
        <ocena > 8 / 10 </ocena>
        <opis >By odzyskać swój dom, brzydki ogr z gadatliwym osłem wyruszają uwolnić piękną księżniczkę.</opis>
    </FILM>
    <FILM>
        <tytul >Avatar</tytul>
        <ocena > 8 / 10 </ocena>
        <opis >Jake, sparaliżowany były komandos, otrzymuje misję i zostaje wysłany na planetę Pandora, gdzie zaprzyjaźnia się z lokalną społecznością oraz postanawia jej pomóc. </opis>
    </FILM>
    <FILM>
        <tytul >Titanic</tytul>
        <ocena > 8 / 10 </ocena>
        <opis >Rok 1912, brytyjski statek Titanic wyrusza w swój dziewiczy rejs do USA. Na pokładzie emigrant Jack przypadkowo spotyka arystokratkę Rose. </opis>
    </FILM>
    <FILM>
        <tytul >Gladiator</tytul>
        <ocena > 8 / 10 </ocena>
        <opis >Generał Maximus - prawa ręka cesarza, szczęśliwy mąż i ojciec - w jednej chwili traci wszystko. Jako niewolnik-gladiator musi walczyć na arenie o przeżycie.</opis>
    </FILM>
    <FILM>
        <tytul >Kac Vegas</tytul>
        <ocena > 8 / 10 </ocena>
        <opis >Czterech przyjaciół spędza wieczór kawalerski w Las Vegas. Następnego dnia okazuje się, że zgubili pana młodego i nic nie pamiętają.</opis>
    </FILM>
</FILMY>
